### ISSUE TITLE
Unhandled Runtime Error- UserProfile.tsx

### ISSUE THREAD

**Issue by batoulalkarim** [kinbaApp/medusa-kinba#12]
Line 226 is erroring out where we are displaying the price in ETH. "invalid BigNumber value"

![Screen Shot 2023-03-16 at 12 50 59 PM](https://user-images.githubusercontent.com/95138778/225693589-c3fbb99b-f9cd-4bb1-a46d-65f0d6c9464b.png)

**Comment by sa8** [comment]
fixed with commit [dafaafa](https://github.com/kinbaApp/medusa-kinba/commit/dafaafa5e92ae334e805c5ebb1f6fc731367649b)
