### ISSUE TITLE
on discover page, creator field has dark background

### ISSUE THREAD

**Issue by sa8** [kinbaApp/medusa-kinba#23]
<img width="406" alt="Screenshot 2023-03-17 at 23 02 32" src="https://user-images.githubusercontent.com/9461485/226066817-ada04aa3-718d-48a4-a3d9-f1a9d4823328.png">

**Comment by batoulalkarim** [comment]
This was because we had switched the app to "dark mode" before we removed the header with the theme switcher. I switched the apps theme to light and it is now fixed. If you wish to implement theme switcher in the app I can add it back!
