### ISSUE TITLE
make the header style similar to the style of the main page

### ISSUE THREAD

**Issue by sa8** [kinbaApp/medusa-kinba#5]
Could we have the same background for the header and the main page? or simithing similar?
<img width="1257" alt="Screenshot 2023-03-15 at 23 23 40" src="https://user-images.githubusercontent.com/9461485/225465650-f5e02a3f-aa32-4aa5-8428-895e4e947262.png">

**Comment by sa8** [comment]
Other option: remove the header and have the connect wallet and signing button on the right side instead (above suggestions)

**Comment by sa8** [comment]
We're going with option 2 (remove header)

**Comment by batoulalkarim** [comment]
I'm making a reusable component that we can put in every page on the right hand side
